### ISSUE TITLE
Releases are associated by the organization

### ISSUE THREAD

**Issue by jembach** [eclass/semantic-release-sentry-releases#293]
Hi,

i have recently noticed a special decision made by the sentry team.
Releases are not associated by a project rather than with the hole organization. The problem is explained [here](https://github.com/getsentry/sentry-cli/issues/482).

So my idea would be to add an additional argument for this plugin where I can set optional a prefix to the release to made the release unique.

Or do you have an other better approach to solve this issue?

I would also implement it because I will need this feature.

**Comment by lgaticaq** [comment]
Resolved in #310
