### ISSUE TITLE
TOKEN format should be compatible with official sentry one

### ISSUE THREAD

**Issue by PeterMK85** [eclass/semantic-release-sentry-releases#75]
https://github.com/eclass/semantic-release-sentry-releases#environment-variables
https://docs.sentry.io/cli/configuration/#to-authenticate-manually

`SENTRY_TOKEN` vs `SENTRY_AUTH_TOKEN`

Ofc If I not missed it :)

**Comment by lgaticaq** [comment]
Thanks. apply suggestion in [v2.0.0](https://github.com/eclass/semantic-release-sentry-releases/releases/tag/v2.0.0)
